// Color
const SCENE_BACKGROUND = 0x181817
const DEFAULT_SPRITE_COLOR = 0xffffff;
const RAYCASTED_SPRITE_COLOR = 0xe57373;

// Opacity
const VISITED_SPRITE_OPACITY = 0.5;

// Sprite
const SPRITE_FRAME_DIMENSION = 4;
const FOCUSED_SPRITE_WINDOW_RATIO = 0.7;
const SPRITE_SPAWN_PER_LOAD = 1000;

// Camera & Fog & Raycaster
const DEFAULT_NEAR = 3;
const DEFAULT_FAR = 50;
const FOCUS_FOG_FAR = 10;

const VIEW_RADIUS = DEFAULT_FAR * 0.5;
const SPAWN_RADIUS = DEFAULT_FAR * 2;

// Tween durations
const TWEEN_ZOOM_IN = 1000;
const TWEEN_ZOOM_OUT = 500;

// Controls
const DEFAULT_ROLL_SPEED = Math.PI/6;
const DEFAULT_MOVEMENT_SPEED = 30;
const ZOOM_IN_DURATION = 800;
const ZOOM_OUT_DURATION = 500;
